package derp.immersivehotbar.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

import java.awt.*;

import static derp.immersivehotbar.config.ImmersiveHotbarConfig.*;

public class ImmersiveHotbarConfigScreen {
    public static Screen create(Screen parent) {
        return YetAnotherConfigLib.createBuilder()
                .title(Text.translatable("immersivehotbar.title"))

                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("immersivehotbar.category.visuals_behavior"))
                        .tooltip(Text.translatable("immersivehotbar.tooltip.visuals_behavior"))

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("immersivehotbar.group.hotbar_appearance"))
                                .description(OptionDescription.of(Text.translatable("immersivehotbar.group.hotbar_appearance.desc")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.tooltip_animation"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.tooltip_animation.desc")))
                                        .controller(TickBoxControllerBuilder::create)
                                        .binding(true, () -> immersiveToolTip, val -> immersiveToolTip = val)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.text_scaling"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.text_scaling.desc")))
                                        .controller(TickBoxControllerBuilder::create)
                                        .binding(true, () -> textScales, val -> textScales = val)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.selected_scale"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.selected_scale.desc")))
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.1f, 2.0f).step(0.1f))
                                        .binding(1.2f, () -> selectedItemSize, val -> selectedItemSize = val)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.unselected_scale"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.unselected_scale.desc")))
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.1f, 1.0f).step(0.1f))
                                        .binding(1.0f, () -> nonSelectedItemSize, val -> nonSelectedItemSize = val)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.shrink_speed"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.shrink_speed.desc")))
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(1f, 5.0f).step(0.1f))
                                        .binding(2.5f, () -> shrinkAnimationSpeed, val -> shrinkAnimationSpeed = val)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("immersivehotbar.group.selection_behavior"))
                                .description(OptionDescription.of(Text.translatable("immersivehotbar.group.selection_behavior.desc")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.should_grow"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.should_grow.desc")))
                                        .controller(TickBoxControllerBuilder::create)
                                        .binding(true, () -> shouldItemGrowWhenSelected, val -> shouldItemGrowWhenSelected = val)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.tool_animates"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.tool_animates.desc")))
                                        .controller(TickBoxControllerBuilder::create)
                                        .binding(false, () -> toolAnimates, val -> toolAnimates = val)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.weapon_animates"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.weapon_animates.desc")))
                                        .controller(TickBoxControllerBuilder::create)
                                        .binding(false, () -> weaponAnimates, val -> weaponAnimates = val)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("immersivehotbar.group.glow_effects"))
                                .description(OptionDescription.of(Text.translatable("immersivehotbar.group.glow_effects.desc")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.durability_glow"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.durability_glow.desc")))
                                        .controller(TickBoxControllerBuilder::create)
                                        .binding(false, () -> lowDurabilityGlow, val -> lowDurabilityGlow = val)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.glow_threshold"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.glow_threshold.desc")))
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.0f, 1.0f).step(0.01f))
                                        .binding(0.8f, () -> durabilityGlowThreshold, val -> durabilityGlowThreshold = val)
                                        .build())
                                .build())

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("immersivehotbar.group.extras"))
                                .description(OptionDescription.of(Text.translatable("immersivehotbar.group.extras.desc")))
                                .option(Option.<shouldShowBackground>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.show_background"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.show_background.desc")))
                                        .controller(opt -> EnumControllerBuilder.create(opt).enumClass(shouldShowBackground.class))
                                        .binding(shouldShowBackground.DISABLED, () -> showBackground, val -> showBackground = val)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.selection_color"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.selection_color.desc")))
                                        .controller(opt -> ColorControllerBuilder.create(opt).allowAlpha(true))
                                        .binding(new Color(255, 255, 255, 127), () -> hotbarSelectionColor, val -> hotbarSelectionColor = val)
                                        .build())
                                .build())
                        .build())

                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("immersivehotbar.category.animation"))
                        .tooltip(Text.translatable("immersivehotbar.tooltip.animation"))

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("immersivehotbar.group.bounce_smoothness"))
                                .description(OptionDescription.of(Text.translatable("immersivehotbar.group.bounce_smoothness.desc")))
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.bouncy_animation"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("immersivehotbar.option.bouncy_animation.desc"))
                                                .webpImage(Identifier.of("immersive-hotbar", "textures/gui/bouncy_animation.webp"))
                                                .build())
                                        .controller(TickBoxControllerBuilder::create)
                                        .binding(false, () -> bouncyAnimation, val -> bouncyAnimation = val)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.bounce_stiffness"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.bounce_stiffness.desc")))
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.1f, 1f).step(0.1f))
                                        .binding(0.3f, () -> bouncyStiffness, val -> bouncyStiffness = val)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.bounce_damping"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.bounce_damping.desc")))
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.1f, 0.8f).step(0.1f))
                                        .binding(0.2f, () -> bouncyDamping, val -> bouncyDamping = val)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.tools_ignore_bounce"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.tools_ignore_bounce.desc")))
                                        .controller(TickBoxControllerBuilder::create)
                                        .binding(false, () -> toolsIgnoreBounce, val -> toolsIgnoreBounce = val)
                                        .build())
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.weapons_ignore_bounce"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.weapons_ignore_bounce.desc")))
                                        .controller(TickBoxControllerBuilder::create)
                                        .binding(false, () -> weaponsIgnoreBounce, val -> weaponsIgnoreBounce = val)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.pop_scale"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.pop_scale.desc")))
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.1f, 0.9f).step(0.1f))
                                        .binding(0.5f, () -> animationIntensity, val -> animationIntensity = val)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("immersivehotbar.option.animation_smoothness"))
                                        .description(OptionDescription.of(Text.translatable("immersivehotbar.option.animation_smoothness.desc")))
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt).range(0.0f, 1.0f).step(0.1f))
                                        .binding(0.1f, () -> animationSpeed, val -> animationSpeed = val)
                                        .build())
                                .build())
                        .build())

                .save(ImmersiveHotbarConfigHandler.HANDLER::save)

                .build()
                .generateScreen(parent);
    }
}
